apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: mariadb
spec:
  selector:
    app: php
  type: NodePort
  ports:
  - nodePort: 31733
    port: 8080
    protocol: TCP
    targetPort: 8080
